name: Compile VAC
# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-vac:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile VAC
        uses: arduino/compile-sketches@v1
        with:
          fqbn:
            - arduino-beta:mbed:envie_m7
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./vac.ino
          libraries: |
            # The "blink" sketch being compiled in this demo doesn't use any libraries, so just use an empty list
            - 
